# Generated by Django 4.2 on 2023-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlisting_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="active_status",
            field=models.BooleanField(default=True),
        ),
    ]
