# Generated by Django 4.2 on 2023-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_auctionlisting_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="listings",
        ),
        migrations.AddField(
            model_name="bid",
            name="listings",
            field=models.ManyToManyField(to="auctions.auctionlisting"),
        ),
    ]
