# Generated by Django 4.2 on 2023-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_watchlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fashion", "Fashion"),
                    ("Toys", "Toys"),
                    ("Electronics", "Electornics"),
                    ("Home", "Home"),
                    ("Outdoors", "Outdoors"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
