# Generated by Django 4.2 on 2023-05-30 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_auctionlisting_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="listings",
            field=models.ManyToManyField(to="auctions.auctionlisting"),
        ),
        migrations.AddField(
            model_name="bids",
            name="place_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="0.00", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="bids",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
