# Generated by Django 4.2 on 2023-05-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_bids_listings_bids_place_bid_bids_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="place_bid",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
        ),
    ]
